// 95 Forward — the action queue ranking engine (Initiative 23).
//
// This is what makes The Board a coach rather than a list: "here is what to do next, by name, and
// here is why" — ranked, reasoned, and overridable.
//
// THREE THINGS ARE DELIBERATELY NOT GENERATED BY A MODEL, and all three for the same reason:
//
//   1. THE STATUS LABEL is a closed enum of seven words. Free-text status drifts between runs —
//      "At risk" becomes "Needs attention" becomes "Urgent" — and the moment the labels drift the
//      red/amber/green vocabulary stops being learnable. A user should recognise the colour and the
//      word without reading the sentence.
//
//   2. THE RATIONALE is a template with computed slots. A user who refreshes and sees different
//      reasoning for identical data has been told the tool is guessing, and nothing in a demo is
//      reproducible. Templates plus real superlatives get very close to the designed copy and stay
//      honest; when no superlative applies we fall back to the rule's own statement rather than
//      inventing one.
//
//   3. THE ORDER is arithmetic over I19's what-ifs. Impact is measured, never assumed.
//
// PURE over a snapshot, like every other computation in this package. Persistence (pin, dismiss,
// the event log) lives in @95forward/db; the engine takes decisions as an input.

import {
  computeQualification,
  isPreCloseStage,
  type ForwardStage,
  FORWARD_STAGES,
} from "./forward";
import type { Clock, ForwardSettings } from "./forward-settings";
import {
  computeMetrics,
  evaluateWhatIf,
  scopeMatches,
  type MetricScope,
  type MetricsSnapshot,
  type SnapshotOpportunity,
  type SnapshotPartner,
} from "./forward-metrics";
import {
  checkScope,
  type CheckDefinition,
  type Finding,
  type ResolutionAction,
} from "./forward-checks";
import type { ResolvedEntry } from "./rules-catalogue";

const DAY_MS = 24 * 60 * 60 * 1000;

// -------------------------------------------------------------------------------------------
// The closed status enum
// -------------------------------------------------------------------------------------------

export const QUEUE_STATUS_LABELS = [
  "at_risk",
  "blocked",
  "unasked",
  "on_track",
  "closing",
  "decaying",
  "cold",
] as const;
export type QueueStatusLabel = (typeof QUEUE_STATUS_LABELS)[number];

export const QUEUE_HEALTHS = ["moving", "slowing", "stuck"] as const;
export type QueueHealth = (typeof QUEUE_HEALTHS)[number];

/** One health per label, and every label has one. The colour vocabulary hangs off this. */
export const STATUS_HEALTH: Record<QueueStatusLabel, QueueHealth> = {
  on_track: "moving",
  closing: "moving",
  blocked: "slowing",
  decaying: "slowing",
  cold: "slowing",
  at_risk: "stuck",
  unasked: "stuck",
};

/** Human wording, so the label is rendered from one place rather than re-cased per screen. */
export const STATUS_LABEL_TEXT: Record<QueueStatusLabel, string> = {
  at_risk: "AT RISK",
  blocked: "BLOCKED",
  unasked: "UNASKED",
  on_track: "ON TRACK",
  closing: "CLOSING",
  decaying: "DECAYING",
  cold: "COLD",
};

const STATUS_SET: ReadonlySet<string> = new Set(QUEUE_STATUS_LABELS);

/**
 * Runtime closure check, not merely a type.
 *
 * A type-level union is erased at runtime, and the one thing that must never happen is a label
 * reaching a screen that has no colour for it. Called on every emitted item.
 */
export function assertStatusLabel(value: string): QueueStatusLabel {
  if (!STATUS_SET.has(value)) {
    throw new Error(
      `Unknown queue status "${value}". The status enum is closed: ${QUEUE_STATUS_LABELS.join(", ")}.`,
    );
  }
  return value as QueueStatusLabel;
}

// -------------------------------------------------------------------------------------------
// The seven rules
// -------------------------------------------------------------------------------------------

export const RANKING_RULE_IDS = [
  "live-ask-silence",
  "prospect-ahead-of-us",
  "visits-without-specific-ask",
  "visit-within-7d-unprepped",
  "verbal-agreement-unwritten",
  "intro-offered-unused",
  "partner-path-unused",
] as const;
export type RankingRuleId = (typeof RANKING_RULE_IDS)[number];

export type NextActionKind =
  | "follow-up-to-close"
  | "get-ask-approved"
  | "make-specific-ask"
  | "prep-the-visit"
  | "get-it-in-writing"
  | "use-introduction"
  | "ask-partner"
  // The two below are never produced by a RULE — they are the stage-derived fallback for a record
  // that fires nothing, which Opportunity Detail needs because it must work for ANY opportunity
  // while the queue only ever shows the ones that fire. Added in I26.
  | "get-the-visit"
  | "steward-the-gift";

export interface NextAction {
  readonly kind: NextActionKind;
  readonly label: string;
  /** What the action operates on. I28 drafts the artifact; this is only the contract. */
  readonly target: {
    readonly opportunityId: string;
    readonly prospectId: string;
    readonly partnerId?: string;
    readonly partnerName?: string;
  };
}

/** Effective parameter values for one rule, already resolved through I22's overrides. */
export type RuleParams = Readonly<Record<string, number | string | readonly string[]>>;

export interface RankingContext {
  readonly opportunity: SnapshotOpportunity;
  readonly snapshot: MetricsSnapshot;
  readonly now: Date;
  readonly today: string;
  readonly qualified: boolean;
  readonly missingBlockingKeys: readonly string[];
  /** Days since the last logged contact; null when there has never been one. */
  readonly silenceDays: number | null;
  /** Signed: negative means the close date has passed. Null when no date is set. */
  readonly daysToClose: number | null;
  readonly params: RuleParams;
}

export interface RankingRule {
  readonly id: RankingRuleId;
  /** The label this rule declares when it is primary. One source for the value, never two. */
  readonly statusLabel: QueueStatusLabel;
  applies(ctx: RankingContext): boolean;
  nextAction(ctx: RankingContext): NextAction;
  /**
   * The same structured control I20's findings carry, reusing I20's CLOSED `ResolutionKind` rather
   * than widening it. Four of the seven land on an exact kind; the rest use `set-field`, which is
   * honest about being "go and change something on the record" — inventing an eighth kind would
   * change I20's contract to describe work that is not a contradiction.
   */
  resolution(ctx: RankingContext): ResolutionAction;
}

function has(ctx: RankingContext, key: string): boolean {
  return ctx.opportunity.confirmedMilestoneKeys.includes(key);
}

function num(ctx: RankingContext, key: string, fallback: number): number {
  const value = ctx.params[key];
  return typeof value === "number" ? value : fallback;
}

/** The first partner who offered an introduction we never took up. */
export function unusedIntroPartner(opportunity: SnapshotOpportunity): SnapshotPartner | undefined {
  return opportunity.partners.find((p) => p.introOfferedAt !== null && p.introUsedAt === null);
}

/** The first partner nobody has ever asked to open the door. */
export function unaskedPartner(opportunity: SnapshotOpportunity): SnapshotPartner | undefined {
  return opportunity.partners.find(
    (p) => p.askedToOpenDoorAt === null && p.introOfferedAt === null,
  );
}

function daysSince(iso: string | null, now: Date): number | null {
  if (!iso) return null;
  return Math.floor((now.getTime() - new Date(iso).getTime()) / DAY_MS);
}

export const RANKING_RULES: readonly RankingRule[] = [
  {
    id: "live-ask-silence",
    statusLabel: "at_risk",
    applies(ctx) {
      // "Live" means the ask has actually been made — silence before an ask is not a failure, it is
      // a pipeline that has not started. Flagging it would bury the real ones.
      if (!has(ctx, "specific_ask_made")) return false;
      if (ctx.silenceDays === null) return false;
      // Per-stage cadence, not one global number: the design says "cadence for this stage · every
      // 14 days", and a get-the-visit prospect legitimately goes quiet for a month.
      const cadence = num(ctx, `cadence.${ctx.opportunity.stage}`, 21);
      return ctx.silenceDays > cadence;
    },
    nextAction: (ctx) => ({
      kind: "follow-up-to-close",
      label: "Follow up to close",
      target: { opportunityId: ctx.opportunity.id, prospectId: ctx.opportunity.prospectId },
    }),
    resolution: () => ({ kind: "re-date-or-close", label: "Re-date it or close it" }),
  },
  {
    id: "prospect-ahead-of-us",
    statusLabel: "blocked",
    applies(ctx) {
      // They have named a date, or put a meeting in the diary. Either way they have moved and we
      // have not: the ask is not internally cleared.
      const theyCommitted =
        has(ctx, "close_date_confirmed") || ctx.opportunity.nextVisitAt !== null;
      return theyCommitted && !has(ctx, "ask_approved_by_leader");
    },
    nextAction: (ctx) => ({
      kind: "get-ask-approved",
      label: "Get the ask approved",
      target: { opportunityId: ctx.opportunity.id, prospectId: ctx.opportunity.prospectId },
    }),
    resolution: () => ({
      kind: "confirm-milestone",
      label: "Confirm the ask is approved",
      targetMilestone: "ask_approved_by_leader",
    }),
  },
  {
    id: "visits-without-specific-ask",
    statusLabel: "unasked",
    applies(ctx) {
      if (has(ctx, "specific_ask_made")) return false;
      return ctx.opportunity.visitCount >= num(ctx, "visitThreshold", 2);
    },
    nextAction: (ctx) => ({
      kind: "make-specific-ask",
      label: "Make the specific ask",
      target: { opportunityId: ctx.opportunity.id, prospectId: ctx.opportunity.prospectId },
    }),
    resolution: () => ({ kind: "record-ask", label: "Record the ask you made" }),
  },
  {
    id: "visit-within-7d-unprepped",
    statusLabel: "on_track",
    applies(ctx) {
      const visitInDays = ctx.opportunity.nextVisitAt
        ? -(daysSince(ctx.opportunity.nextVisitAt, ctx.now) ?? 0)
        : null;
      if (visitInDays === null || visitInDays < 0) return false;
      if (visitInDays > num(ctx, "windowDays", 7)) return false;
      // Two ways to be unprepped, and they are different failures: no brief at all, or a brief with
      // no number in it that anybody internally has agreed to.
      return !ctx.opportunity.nextVisitPrepared || !has(ctx, "ask_approved_by_leader");
    },
    nextAction: (ctx) => ({
      kind: "prep-the-visit",
      label: "Prep the visit",
      target: { opportunityId: ctx.opportunity.id, prospectId: ctx.opportunity.prospectId },
    }),
    resolution: () => ({ kind: "set-field", label: "Write the prep brief", targetField: "goal" }),
  },
  {
    id: "verbal-agreement-unwritten",
    statusLabel: "closing",
    applies(ctx) {
      if (!has(ctx, "amount_agreed") || has(ctx, "confirmed_in_writing")) return false;
      const agreedDays = daysSince(
        ctx.opportunity.milestoneConfirmedAt["amount_agreed"] ?? null,
        ctx.now,
      );
      // No recorded date means we cannot say it is overdue, so we do not claim it is.
      if (agreedDays === null) return false;
      return agreedDays > num(ctx, "graceDays", 14);
    },
    nextAction: (ctx) => ({
      kind: "get-it-in-writing",
      label: "Get it in writing",
      target: { opportunityId: ctx.opportunity.id, prospectId: ctx.opportunity.prospectId },
    }),
    resolution: () => ({
      kind: "confirm-milestone",
      label: "Confirm it in writing",
      targetMilestone: "confirmed_in_writing",
    }),
  },
  {
    id: "intro-offered-unused",
    statusLabel: "decaying",
    applies(ctx) {
      // Once the ask has been made, "you never used the introduction" stops being the useful thing
      // to say about the record — the door is open. Without this guard a prospect with two
      // opportunities gets coached to walk through a door they are already standing inside.
      if (has(ctx, "specific_ask_made")) return false;
      const partner = unusedIntroPartner(ctx.opportunity);
      if (!partner) return false;
      const offeredDays = daysSince(partner.introOfferedAt, ctx.now);
      if (offeredDays === null) return false;
      return offeredDays > num(ctx, "graceDays", 14);
    },
    nextAction(ctx) {
      const partner = unusedIntroPartner(ctx.opportunity);
      return {
        kind: "use-introduction",
        label: `Get the visit through ${partner?.name ?? "your partner"}`,
        target: {
          opportunityId: ctx.opportunity.id,
          prospectId: ctx.opportunity.prospectId,
          partnerId: partner?.id,
          partnerName: partner?.name,
        },
      };
    },
    resolution: () => ({ kind: "set-field", label: "Log the introduction as used" }),
  },
  {
    id: "partner-path-unused",
    statusLabel: "cold",
    applies(ctx) {
      // No ask made yet — once we are in conversation, "nobody opened the door" stops being the
      // useful thing to say about this record.
      if (has(ctx, "specific_ask_made")) return false;
      return unaskedPartner(ctx.opportunity) !== undefined;
    },
    nextAction(ctx) {
      const partner = unaskedPartner(ctx.opportunity);
      return {
        kind: "ask-partner",
        label: `Ask ${partner?.name ?? "your partner"} to open the door`,
        target: {
          opportunityId: ctx.opportunity.id,
          prospectId: ctx.opportunity.prospectId,
          partnerId: partner?.id,
          partnerName: partner?.name,
        },
      };
    },
    resolution: () => ({ kind: "set-field", label: "Log the partner ask" }),
  },
];

export const RANKING_RULES_BY_ID: ReadonlyMap<string, RankingRule> = new Map(
  RANKING_RULES.map((rule) => [rule.id, rule]),
);

// -------------------------------------------------------------------------------------------
// Impact — dollars in play, measured through I19 rather than assumed
// -------------------------------------------------------------------------------------------

export interface ImpactInput {
  readonly snapshot: MetricsSnapshot;
  readonly scope: MetricScope;
  readonly settings: ForwardSettings;
  readonly clock: Clock;
  readonly opportunity: SnapshotOpportunity;
  readonly qualified: boolean;
}

/**
 * What this opportunity moves, in cents.
 *
 * Two cases, computed the same way so the comparison between them is honest:
 *
 *   UNQUALIFIED — what qualifying it would ADD to qualified asks on the table. The hypothesis
 *   confirms every blocking milestone; the delta is the upside currently not counted.
 *
 *   QUALIFIED — what losing it would WITHHOLD. The hypothesis removes it; the delta is what is
 *   counted today and would stop being.
 *
 * Both come back positive and both mean "dollars in play", which is what makes it legitimate to
 * rank a $250,000 unqualified ask against a $300,000 qualified one in the same list. Neither is the
 * bare `amountCents` — a late-stage opportunity that has slipped out of the fiscal period
 * contributes nothing to this period's number, and this arithmetic says so.
 */
export function impactCents(input: ImpactInput): number {
  const { snapshot, scope, settings, clock, opportunity, qualified } = input;

  const overrides = qualified
    ? { excludeOpportunityIds: [opportunity.id] }
    : {
        milestonePatches: {
          [opportunity.id]: [
            ...new Set([
              ...opportunity.confirmedMilestoneKeys,
              ...snapshot.definitions.filter((d) => d.blocking).map((d) => d.key),
            ]),
          ],
        },
      };

  const whatIf = evaluateWhatIf({ snapshot, scope, settings, clock, overrides });
  return Math.abs(whatIf.qualifiedAsksDeltaCents);
}

/**
 * How much sooner-ness multiplies the score.
 *
 * Linear from 1 at the horizon to `maxMultiplier` on the close date, and pinned at the maximum once
 * the date has passed — a date that has gone by is the most urgent thing on the board, not the
 * least. No close date means no claim: urgency 1, and the item ranks on impact alone.
 */
export function urgencyFactor(
  daysToClose: number | null,
  horizonDays: number,
  maxMultiplier: number,
): number {
  if (daysToClose === null) return 1;
  if (daysToClose <= 0) return maxMultiplier;
  if (daysToClose >= horizonDays) return 1;
  const closeness = (horizonDays - daysToClose) / horizonDays;
  return 1 + (maxMultiplier - 1) * closeness;
}

// -------------------------------------------------------------------------------------------
// Portfolio superlatives — what makes a rationale say "largest" and mean it
// -------------------------------------------------------------------------------------------

export interface PortfolioSuperlatives {
  /** Largest amount among opportunities where the ask has actually been made. */
  readonly largestLiveAskId: string | null;
  /** Longest silence among those same live asks. */
  readonly longestSilenceId: string | null;
  readonly longestSilenceDays: number | null;
  /** Largest amount among everything in scope and still open. */
  readonly biggestOnBoardId: string | null;
  /** Oldest unused introduction offer. */
  readonly oldestUnusedIntroId: string | null;
}

export function computeSuperlatives(
  opportunities: readonly SnapshotOpportunity[],
  now: Date,
): PortfolioSuperlatives {
  const open = opportunities.filter((o) => o.status === "open");
  // LIVE means still outstanding: the ask has been made and they have not yet confirmed it in
  // writing. A gift they have already put in writing is not an ask you are waiting on, so counting
  // it would make "the largest live ask in your portfolio" name the wrong record — and the whole
  // value of a superlative is that it is true when it is said.
  const live = open.filter(
    (o) =>
      o.confirmedMilestoneKeys.includes("specific_ask_made") &&
      !o.confirmedMilestoneKeys.includes("confirmed_in_writing"),
  );

  const biggest = (rows: readonly SnapshotOpportunity[]) =>
    rows.reduce<SnapshotOpportunity | null>(
      (best, o) =>
        !best ||
        o.amountCents > best.amountCents ||
        (o.amountCents === best.amountCents && o.id < best.id)
          ? o
          : best,
      null,
    );

  let longestSilence: { id: string; days: number } | null = null;
  for (const o of live) {
    const days = daysSince(o.lastContactAt, now);
    if (days === null) continue;
    if (!longestSilence || days > longestSilence.days) longestSilence = { id: o.id, days };
  }

  let oldestIntro: { id: string; at: number } | null = null;
  for (const o of open) {
    const partner = unusedIntroPartner(o);
    if (!partner?.introOfferedAt) continue;
    const at = new Date(partner.introOfferedAt).getTime();
    if (!oldestIntro || at < oldestIntro.at) oldestIntro = { id: o.id, at };
  }

  return {
    largestLiveAskId: biggest(live)?.id ?? null,
    longestSilenceId: longestSilence?.id ?? null,
    longestSilenceDays: longestSilence?.days ?? null,
    biggestOnBoardId: biggest(open)?.id ?? null,
    oldestUnusedIntroId: oldestIntro?.id ?? null,
  };
}

// -------------------------------------------------------------------------------------------
// Rationale — deterministic templates over those superlatives
// -------------------------------------------------------------------------------------------

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

function dayPhrase(n: number): string {
  return `${n} ${plural(n, "day", "days")}`;
}

/**
 * One sentence explaining the rank.
 *
 * The superlative branches come first because they are the ones that read like coaching rather than
 * like a field dump — "the largest live ask in your portfolio has gone silent longest" is a claim
 * about the board, and it is true when it is said. When no superlative applies we say the smaller
 * true thing, and if even that is unavailable the caller falls back to the rule's own statement.
 * Nothing here invents a fact it has not been handed.
 */
export function rationaleFor(
  ruleId: RankingRuleId,
  ctx: RankingContext,
  sup: PortfolioSuperlatives,
): string | null {
  const o = ctx.opportunity;
  const closeClause =
    ctx.daysToClose === null
      ? null
      : ctx.daysToClose < 0
        ? `it is ${dayPhrase(-ctx.daysToClose)} past its close date`
        : `it closes in ${dayPhrase(ctx.daysToClose)}`;

  switch (ruleId) {
    case "live-ask-silence": {
      if (ctx.silenceDays === null) return null;
      const isLargest = sup.largestLiveAskId === o.id;
      const isLongest = sup.longestSilenceId === o.id;
      const subject = isLargest ? "The largest live ask in your portfolio" : "This live ask";
      const silence = isLongest
        ? "has gone silent longest"
        : `has gone silent for ${dayPhrase(ctx.silenceDays)}`;
      return closeClause ? `${subject} ${silence} — and ${closeClause}.` : `${subject} ${silence}.`;
    }

    case "prospect-ahead-of-us": {
      const isBiggest = sup.biggestOnBoardId === o.id;
      // The sharpest version of this is true only when the approval is the LAST thing standing in
      // the way. When other milestones are missing too, saying "the only milestone missing" would
      // be a lie, so the sentence changes.
      const onlyOurs =
        ctx.missingBlockingKeys.length === 0 &&
        !o.confirmedMilestoneKeys.includes("ask_approved_by_leader");
      if (isBiggest && onlyOurs) {
        return "This is the biggest amount on your board and the only milestone missing is the one only you can do.";
      }
      if (o.nextVisitAt) {
        return "They have put a meeting in the diary that we are not yet internally cleared to walk into.";
      }
      return "They have given you a date and the ask has still not been approved internally.";
    }

    case "visits-without-specific-ask": {
      const times = `${o.visitCount} ${plural(o.visitCount, "time", "times")}`;
      return `You have been in front of them ${times} and never asked for anything specific.`;
    }

    case "visit-within-7d-unprepped": {
      const days = o.nextVisitAt ? -(daysSince(o.nextVisitAt, ctx.now) ?? 0) : null;
      if (days === null) return null;
      const when = days === 0 ? "today" : `in ${dayPhrase(days)}`;
      return o.nextVisitPrepared
        ? `The visit is ${when} and no ask amount has been agreed internally.`
        : `The visit is ${when} and there is no prep brief.`;
    }

    case "verbal-agreement-unwritten": {
      const agreedDays = daysSince(o.milestoneConfirmedAt["amount_agreed"] ?? null, ctx.now);
      if (agreedDays === null) return null;
      return `They agreed to the amount ${dayPhrase(agreedDays)} ago and nothing has been put in writing.`;
    }

    case "intro-offered-unused": {
      const partner = unusedIntroPartner(o);
      if (!partner) return null;
      if (sup.oldestUnusedIntroId === o.id) {
        return "A warm introduction that nobody acted on is the fastest asset you own to lose.";
      }
      const offeredDays = daysSince(partner.introOfferedAt, ctx.now);
      return offeredDays === null
        ? null
        : `${partner.name} offered an introduction ${dayPhrase(offeredDays)} ago and it has not been used.`;
    }

    case "partner-path-unused": {
      const partner = unaskedPartner(o);
      if (!partner) return null;
      const role = partner.role ? `${partner.name} (${partner.role})` : partner.name;
      return `${role} can open this door and has never been asked.`;
    }
  }
}

// -------------------------------------------------------------------------------------------
// Ranking
// -------------------------------------------------------------------------------------------

export type DecisionKind = "pin" | "dismiss";

/**
 * A human overriding the guidance.
 *
 * `dataVersion` is what the opportunity looked like when the decision was made. A dismissal that
 * outlived the data it was about would silently hide a problem that has since got worse, so a
 * dismissal is only honoured while the version still matches. See `isDismissalLive`.
 */
export interface QueueDecision {
  readonly kind: DecisionKind;
  readonly opportunityId: string;
  /** Set for a decision about one I20 finding; null for the whole queue item. */
  readonly ruleId: string | null;
  readonly dataVersion: string;
  readonly decidedAt: string;
}

export interface RankedItem {
  readonly rank: number;
  readonly opportunityId: string;
  readonly prospectId: string;
  readonly initiativeId: string;
  readonly ownerUserId: string | null;
  readonly amountCents: number;
  readonly stage: ForwardStage;
  readonly closeDate: string | null;
  readonly qualified: boolean;
  /** How many times the date has moved and whether they ever drove one of those moves. */
  readonly closeDateMoves: number;
  readonly closeDateMovesProspectSourced: boolean;

  readonly statusLabel: QueueStatusLabel;
  readonly statusText: string;
  readonly health: QueueHealth;

  /** The highest-multiplier firing rule. It declares the label, the action and the rationale. */
  readonly primaryRuleId: RankingRuleId;
  /** Every rule firing on this opportunity, for the chips. */
  readonly firingRuleIds: readonly RankingRuleId[];

  readonly rationale: string;
  readonly nextAction: NextAction;

  readonly impactCents: number;
  readonly multiplier: number;
  readonly urgency: number;
  readonly score: number;
  readonly pinned: boolean;
}

export interface BelowCut {
  readonly count: number;
  readonly cents: number;
  /**
   * Could everything below the cut, together, close this week's gap?
   *
   * The design claims "none of them change this week's number", and a claim is something you
   * compute. Null when there is no goal to measure against — an absent denominator is not a "no".
   */
  readonly changesTheNumber: boolean | null;
}

export interface DayWorkSummary {
  readonly findingCount: number;
  /**
   * Summed effort across the Fix-first findings.
   *
   * Here rather than only on `CheckResult`, which `dayWork` does not return: The Board's
   * "clear them in under three minutes" was summing it from the findings itself, which is the same
   * number computed in two places — and two computations of one number is how they come to
   * disagree. The engine returns seconds; the UI phrases them.
   */
  readonly totalEffortSeconds: number;
  readonly queueCount: number;
  /** The one fact about item #1 that The Board's subtitle needs. Null when the queue is empty. */
  readonly topItemFact: TopItemFact | null;
}

export interface TopItemFact {
  readonly opportunityId: string;
  readonly kind: "idle-days" | "past-close" | "closes-in" | "unasked-visits" | "none";
  readonly value: number | null;
}

export interface DayWorkResult {
  readonly fixFirst: readonly Finding[];
  readonly queue: readonly RankedItem[];
  /**
   * EVERY scored opportunity in scope, ranked, of which `queue` is the first `queue-size`.
   *
   * The Opportunities grid (I29) shows a rank column over the whole portfolio, not the top seven.
   * It reads this rather than re-sorting, because the grid's central claim is that it agrees with
   * The Board — and two sorts of the same scores are exactly how two surfaces come to disagree
   * about which deal is #1 while both look right. `queue` is a slice of this by construction.
   */
  readonly ranked: readonly RankedItem[];
  readonly belowCut: BelowCut;
  readonly summary: DayWorkSummary;
}

export interface DayWorkInput {
  readonly snapshot: MetricsSnapshot;
  readonly scope: MetricScope;
  readonly settings: ForwardSettings;
  readonly clock: Clock;
  /** The org's effective doctrine (I22). Supplies every threshold and multiplier below. */
  readonly resolved: readonly ResolvedEntry[];
  /** Pins and dismissals. */
  readonly decisions?: readonly QueueDecision[];
  /** Current data version per opportunity, for dismissal expiry. */
  readonly dataVersions?: Readonly<Record<string, string>>;
  /** Passed through to I20 so a disabled check disappears from Fix first too. */
  readonly checks?: readonly CheckDefinition[];
}

/** A dismissal holds only while the thing it was about has not moved. */
export function isDismissalLive(
  decision: QueueDecision,
  dataVersions: Readonly<Record<string, string>> | undefined,
): boolean {
  const current = dataVersions?.[decision.opportunityId];
  if (current === undefined) return true;
  return current === decision.dataVersion;
}

function paramsFor(resolved: readonly ResolvedEntry[], id: string): RuleParams {
  return resolved.find((e) => e.id === id)?.values ?? {};
}

function enabled(resolved: readonly ResolvedEntry[], id: string): boolean {
  const entry = resolved.find((e) => e.id === id);
  // A rule nobody registered is not silently on: the catalogue is the authority on what exists.
  return entry ? entry.enabled : false;
}

function globalNumber(
  resolved: readonly ResolvedEntry[],
  id: string,
  key: string,
  fallback: number,
): number {
  const value = resolved.find((e) => e.id === id)?.values[key];
  return typeof value === "number" ? value : fallback;
}

function dayDiff(fromIso: string | null, now: Date): number | null {
  if (!fromIso) return null;
  const target = new Date(`${fromIso}T00:00:00.000Z`).getTime();
  const today = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  return Math.round((target - today) / DAY_MS);
}

/**
 * Everything a rep should do today, in order.
 *
 * `fixFirst` is delegated to I20 rather than re-derived. One ordering authority for contradictions;
 * a second would eventually disagree with the first, and the screen would contradict itself in
 * front of the person it is trying to coach.
 */
export function dayWork(input: DayWorkInput): DayWorkResult {
  const { snapshot, scope, settings, clock, resolved } = input;
  const now = clock.now();
  const today = now.toISOString().slice(0, 10);

  const fixFirst = checkScope({ snapshot, scope, settings, clock, checks: input.checks }).findings;

  const decisions = input.decisions ?? [];
  const pinnedIds = new Set(
    decisions.filter((d) => d.kind === "pin" && d.ruleId === null).map((d) => d.opportunityId),
  );
  const dismissedIds = new Set(
    decisions
      .filter((d) => d.kind === "dismiss" && d.ruleId === null)
      .filter((d) => isDismissalLive(d, input.dataVersions))
      .map((d) => d.opportunityId),
  );

  // PRE-CLOSE ONLY. `celebrate_steward` and `repeat` are closed work — I19 puts them outside the
  // headline number by design, so an action on one moves nothing, and coaching a rep to "follow up
  // to close" a gift that is already being stewarded is advice that makes the tool look stupid.
  // Their silence would also steal the "gone silent longest" superlative from a live ask, where it
  // actually means something.
  const inScope = snapshot.opportunities.filter(
    (o) => scopeMatches(o, scope) && o.status === "open" && isPreCloseStage(o.stage),
  );
  const superlatives = computeSuperlatives(inScope, now);

  const horizon = globalNumber(resolved, "queue-urgency", "horizonDays", 90);
  const maxUrgency = globalNumber(resolved, "queue-urgency", "maxMultiplier", 2);
  const queueSize = globalNumber(resolved, "queue-size", "items", 7);

  const scored: Scored[] = [];

  for (const opportunity of inScope) {
    if (dismissedIds.has(opportunity.id)) continue;
    const item = scoreOpportunity({
      opportunity,
      snapshot,
      scope,
      settings,
      clock,
      resolved,
      now,
      today,
      superlatives,
      horizon,
      maxUrgency,
      pinned: pinnedIds.has(opportunity.id),
    });
    if (item !== null) scored.push(item);
  }

  return finishDayWork({
    fixFirst,
    scored,
    queueSize,
    snapshot,
    scope,
    settings,
    clock,
    now,
  });
}

/** Everything a RankedItem carries except its position, which is only known once all are sorted. */
export type UnrankedItem = Omit<RankedItem, "rank">;
type Scored = UnrankedItem;

interface ScoreInput {
  readonly opportunity: SnapshotOpportunity;
  readonly snapshot: MetricsSnapshot;
  readonly scope: MetricScope;
  readonly settings: ForwardSettings;
  readonly clock: Clock;
  readonly resolved: readonly ResolvedEntry[];
  readonly now: Date;
  readonly today: string;
  readonly superlatives: PortfolioSuperlatives;
  readonly horizon: number;
  readonly maxUrgency: number;
  readonly pinned: boolean;
}

/**
 * Score ONE opportunity against the seven rules.
 *
 * Extracted from `dayWork`'s loop in I26 rather than reimplemented, because Opportunity Detail has
 * to answer "what does this record's rule say" for a record that may sit below the cut or fire
 * nothing at all — and a second implementation of the scoring would eventually disagree with the
 * queue about the same record, in front of the person being coached.
 *
 * Returns null when no enabled rule applies.
 */
function scoreOpportunity(input: ScoreInput): Scored | null {
  const {
    opportunity,
    snapshot,
    scope,
    settings,
    clock,
    resolved,
    now,
    today,
    superlatives,
    horizon,
    maxUrgency,
    pinned,
  } = input;

  {
    const qualification = computeQualification(
      snapshot.definitions,
      opportunity.confirmedMilestoneKeys,
    );

    const silence =
      opportunity.lastContactAt === null
        ? null
        : Math.max(
            0,
            Math.floor((now.getTime() - new Date(opportunity.lastContactAt).getTime()) / DAY_MS),
          );

    const daysToClose = dayDiff(opportunity.closeDate, now);

    const base = {
      opportunity,
      snapshot,
      now,
      today,
      qualified: qualification.qualified,
      missingBlockingKeys: qualification.missingBlocking.map((d) => d.key),
      silenceDays: silence,
      daysToClose,
    };

    const firing: { rule: RankingRule; multiplier: number; ctx: RankingContext }[] = [];
    for (const rule of RANKING_RULES) {
      if (!enabled(resolved, rule.id)) continue;
      const ctx: RankingContext = { ...base, params: paramsFor(resolved, rule.id) };
      if (!rule.applies(ctx)) continue;
      firing.push({ rule, multiplier: num(ctx, "multiplier", 1), ctx });
    }
    if (firing.length === 0) return null;

    // MAXIMUM, not product. An opportunity firing three rules is not three times more urgent than a
    // comparable one firing a single stronger rule — products produce runaway scores that bury
    // everything else and make the ordering impossible to explain to the person being coached.
    // Ties break on the fixed rule order so the primary never jitters.
    const primary = firing.reduce((best, candidate) =>
      candidate.multiplier > best.multiplier ? candidate : best,
    );
    const multiplier = primary.multiplier;

    const impact = impactCents({
      snapshot,
      scope,
      settings,
      clock,
      opportunity,
      qualified: qualification.qualified,
    });
    const urgency = urgencyFactor(daysToClose, horizon, maxUrgency);

    const statusLabel = assertStatusLabel(primary.rule.statusLabel);
    const template = rationaleFor(primary.rule.id, primary.ctx, superlatives);
    const fallback = resolved.find((e) => e.id === primary.rule.id)?.statement ?? primary.rule.id;

    return {
      opportunityId: opportunity.id,
      prospectId: opportunity.prospectId,
      initiativeId: opportunity.initiativeId,
      ownerUserId: opportunity.ownerUserId,
      amountCents: opportunity.amountCents,
      stage: opportunity.stage,
      closeDate: opportunity.closeDate,
      qualified: qualification.qualified,
      closeDateMoves: opportunity.closeDateMoves,
      closeDateMovesProspectSourced: opportunity.closeDateMovesProspectSourced,
      statusLabel,
      statusText: STATUS_LABEL_TEXT[statusLabel],
      health: STATUS_HEALTH[statusLabel],
      primaryRuleId: primary.rule.id,
      firingRuleIds: firing.map((f) => f.rule.id),
      rationale: template ?? fallback,
      nextAction: primary.rule.nextAction(primary.ctx),
      impactCents: impact,
      multiplier,
      urgency,
      score: impact * multiplier * urgency,
      pinned,
    };
  }
}

interface FinishInput {
  readonly fixFirst: readonly Finding[];
  readonly scored: readonly Scored[];
  readonly queueSize: number;
  readonly snapshot: MetricsSnapshot;
  readonly scope: MetricScope;
  readonly settings: ForwardSettings;
  readonly clock: Clock;
  readonly now: Date;
}

function finishDayWork(input: FinishInput): DayWorkResult {
  const { fixFirst, queueSize, snapshot, scope, settings, clock, now } = input;
  const scored = [...input.scored];

  // Pinned first, then score, then opportunity id. The id tie-break is not decoration: identical
  // data must produce an identical order, and a queue that reorders on refresh reads as broken.
  scored.sort((a, b) => {
    if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
    if (b.score !== a.score) return b.score - a.score;
    return a.opportunityId.localeCompare(b.opportunityId);
  });

  const ranked: RankedItem[] = scored.map((item, index) => ({ ...item, rank: index + 1 }));
  const queue: RankedItem[] = ranked.slice(0, Math.max(0, queueSize));

  const remainder = ranked.slice(queue.length);
  const belowCutCents = remainder.reduce((sum, item) => sum + item.impactCents, 0);

  const metrics = computeMetrics({ snapshot, scope, settings, clock });
  const weeklyRequirement = metrics.newAsksNeeded?.perWeek ?? null;

  return {
    fixFirst,
    queue,
    ranked,
    belowCut: {
      count: remainder.length,
      cents: belowCutCents,
      // A claim, so it is computed: could the whole remainder, together, cover what this week
      // demands? Null when no goal is defined for the scope — there is nothing to measure against,
      // and "no" would be an answer we have not earned.
      changesTheNumber: weeklyRequirement === null ? null : belowCutCents >= weeklyRequirement,
    },
    summary: {
      findingCount: fixFirst.length,
      totalEffortSeconds: fixFirst.reduce((sum, finding) => sum + finding.effortSeconds, 0),
      queueCount: queue.length,
      topItemFact: queue[0] ? topItemFactFor(queue[0], snapshot, now) : null,
    },
  };
}

/**
 * The single most quotable number about item #1.
 *
 * Structured, not a sentence: The Board composes "3 broken forecasts, then 7 moves that change the
 * number today. Item #1 is 81 days idle." — the composing belongs to the screen, the facts belong
 * here.
 */
function topItemFactFor(item: RankedItem, snapshot: MetricsSnapshot, now: Date): TopItemFact {
  const opportunity = snapshot.opportunities.find((o) => o.id === item.opportunityId);
  const idle = opportunity ? daysSince(opportunity.lastContactAt, now) : null;
  const days = dayDiff(item.closeDate, now);

  if (item.primaryRuleId === "live-ask-silence" && idle !== null) {
    return { opportunityId: item.opportunityId, kind: "idle-days", value: idle };
  }
  if (item.primaryRuleId === "visits-without-specific-ask" && opportunity) {
    return {
      opportunityId: item.opportunityId,
      kind: "unasked-visits",
      value: opportunity.visitCount,
    };
  }
  if (days !== null && days < 0) {
    return { opportunityId: item.opportunityId, kind: "past-close", value: -days };
  }
  if (days !== null) {
    return { opportunityId: item.opportunityId, kind: "closes-in", value: days };
  }
  if (idle !== null) {
    return { opportunityId: item.opportunityId, kind: "idle-days", value: idle };
  }
  return { opportunityId: item.opportunityId, kind: "none", value: null };
}

// -------------------------------------------------------------------------------------------
// One record — what Opportunity Detail needs and the queue cannot give it
// -------------------------------------------------------------------------------------------

/**
 * The contact cadence the org expects at this stage, in days.
 *
 * Per-stage, not one global number: a get-the-visit prospect legitimately goes a month without
 * contact while an ask waiting on a yes does not. It lives on `live-ask-silence` because that is
 * the rule that acts on it, and reading it from there is what keeps the SILENCE panel's
 * "CADENCE FOR THIS STAGE · EVERY 14 DAYS" true after an org edits its doctrine.
 */
export function stageCadenceDays(
  resolved: readonly ResolvedEntry[],
  stage: ForwardStage,
  fallback = 21,
): number {
  const value = paramsFor(resolved, "live-ask-silence")[`cadence.${stage}`];
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

export interface RankOneInput {
  readonly snapshot: MetricsSnapshot;
  readonly scope: MetricScope;
  readonly settings: ForwardSettings;
  readonly clock: Clock;
  readonly resolved: readonly ResolvedEntry[];
  readonly opportunityId: string;
}

/**
 * Evaluate the seven rules against ONE opportunity, wherever it sits.
 *
 * `dayWork` only returns the top few of the records that fire something, and Opportunity Detail has
 * to work for any record at all — one below the cut, one firing nothing, one a rep opened from a
 * search. This runs the SAME scoring over the same snapshot, so the detail screen and the board can
 * never disagree about why a record ranks.
 *
 * Superlatives are computed over the whole scope, not the one record: "the biggest amount on your
 * board" is a claim about the board, and computing it from a single opportunity would make every
 * record the biggest.
 *
 * Returns null when no enabled rule applies, when the record is out of scope, or when it is closed
 * or past the pre-close stages. Callers fall back to `stageNextAction`.
 */
export function rankOne(input: RankOneInput): UnrankedItem | null {
  const { snapshot, scope, settings, clock, resolved, opportunityId } = input;
  const now = clock.now();
  const today = now.toISOString().slice(0, 10);

  const inScope = snapshot.opportunities.filter(
    (o) => scopeMatches(o, scope) && o.status === "open" && isPreCloseStage(o.stage),
  );
  const opportunity = inScope.find((o) => o.id === opportunityId);
  if (!opportunity) return null;

  return scoreOpportunity({
    opportunity,
    snapshot,
    scope,
    settings,
    clock,
    resolved,
    now,
    today,
    superlatives: computeSuperlatives(inScope, now),
    horizon: globalNumber(resolved, "queue-urgency", "horizonDays", 90),
    maxUrgency: globalNumber(resolved, "queue-urgency", "maxMultiplier", 2),
    pinned: false,
  });
}

const STAGE_ACTION: Record<ForwardStage, { kind: NextActionKind; label: string }> = {
  get_the_visit: { kind: "get-the-visit", label: "Get the visit" },
  prep_the_visit: { kind: "prep-the-visit", label: "Prep the visit" },
  visit_and_ask: { kind: "make-specific-ask", label: "Make the specific ask" },
  follow_up_and_close: { kind: "follow-up-to-close", label: "Follow up to close" },
  celebrate_steward: { kind: "steward-the-gift", label: "Thank them and steward the gift" },
  repeat: { kind: "steward-the-gift", label: "Set up the next conversation" },
};

/**
 * The next action for a record no rule speaks for.
 *
 * A stage IS a statement about what happens next — that is what the six-stage vocabulary is for —
 * so a record with nothing firing is not a record with nothing to do. Opportunity Detail must never
 * render an empty NEXT ACTION panel: a screen that opens with a verdict and then shrugs has
 * undercut its own argument.
 */
export function stageNextAction(stage: ForwardStage, target: NextAction["target"]): NextAction {
  const { kind, label } = STAGE_ACTION[stage];
  return { kind, label, target };
}

export { FORWARD_STAGES };
